config/routes.rb
Rails.application.routes.draw do

  get "/", to: "toys#index", as: "root"
  post "toys", to: "toys#create"
  get "/toy/new", to: "toys#new", as: "new"
  get "/toy/view/:id", to: "toys#view", as: "view"
  delete 'toy/:id', to: 'toys#destroy', as: "delete"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/toy.rb
class Toy < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
  def index
    @toys = Toy.all
    # @toys.destroy
    # redirect_to :root
  end

  def new 
    @new_toy = Toy.new
  end

  def create
    @new_toy = Toy.new(toy_params)
    @new_toy.save
    redirect_to action: "view", id: @new_toy.id
  end

  def view 
    @new_toy = Toy.find(params[:id])
  end

  def update

  end

  def destroy
    @new_toy = Toy.find(params[:id])
    @new_toy.destroy
    redirect_to :root
  end

  private
  def toy_params
    params.require(:toy).permit(:name, :description, :date, :user)
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToyStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_form.html.erb
<%= form_with model: @new_toy do |form|  %>
  <p>
    <%= form.label :name %></p>
    <%= form.text_field :name%>
  </p>

  <p>
    <%= form.label :description %></p>
    <%= form.text_field :description %>
  </p>

  <p>
    <%= form.label :date %></p>
    <%= form.date_field :date%>
  </p>

  <p>
    <%= form.label :description %></p>
    <%= form.text_field :description%>
  </p>

  <p>
    <%= form.submit %>
    <button><%= link_to "Cancel" , root_path()%></button>
  </p>
<% end %>

app/views/toys/index.html.erb
<% if @toys.blank? %>
  <p>There are no toys in the system, add some here - </p>
  <button><%= link_to "Create Toy", new_path() %></button>
<% else %>
  <p>These are the Toys in our system</p>
  <button><%= link_to "Create Toy", new_path() %></button>
  <% @toys.each do |toy| %>
    <ul>
      <li>
        Toy Name:  <%= toy.name %> <br>
        User Name: <%= toy.user %> <br>  
        <%= link_to "view", view_path(toy)%> 
        <button><%= link_to "delete", delete_path(toy), method: :delete, data: {confirm: "Are you sure?"} %></button>
      </li>
    </ul>
  <% end %>
<% end %>

app/views/toys/new.html.erb
<h1> Create Toys </h1>

<%= render "shared/form"%>

app/views/toys/view.html.erb
<h1>Here is your new toy!</h1>

<h3><%= @new_toy.name  %></h3>
<p><%= @new_toy.description %></p>
<p><%= @new_toy.date%></p>
<button><%= link_to "delete", delete_path(@new_toy), method: :delete%></button>
<button><%= link_to "Back", root_path() %></button>